# Generated by Django 5.2 on 2025-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.CharField(choices=[('operating_systems', 'Operating Systems'), ('programming', 'Programming'), ('data_science', 'Data Science'), ('web_development', 'Web Development'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Custom Category'),
        ),
    ]
